### PR TITLE
Localization updates (small changes + new locales ko_KR, pt_BR)

### PR DESCRIPTION
**Pull request by tofi86**
New updates pulled from Transifex.

- [x] ensure every `--help` message has the new `--locale` switch even if it's english
- [x] pull Korean language (68% translated)
- [x] fix `transifex-pull.sh` to allow for `xx_YY` formatted language codes
- [x] check that Java recognized `messages_ko_KR.properties` pattern. Otherwise we need to use Transifex language mappings: https://docs.transifex.com/client/client-configuration#language-mappings
- [x] waiting for final translations by translators

Currently there seems to be a bug which does not pull the Korean language files even though they are above the threshold of 50% translated strings.

This can be included in a possible release v4.1.1

### CODE REVIEW

**Comment by tofi86** [comment]
> Currently there seems to be a bug which does not pull the Korean language files even though they are above the threshold of 50% translated strings.

Maybe because Korean is defined as `ko_KR` (https://www.transifex.com/idpf/teams/28633/ko_KR/) and we don't have a pattern allowing for this? e.g. in `.tx/config`?

Needs to be investigated.

**Comment by tofi86** [comment]
> ... and we don't have a pattern allowing for this? e.g. in `.tx/config`?

That was it. But in the `transifex-pull.sh` script.

Also: NEW languages need to be pulled with with `transifex-pull.sh xx_YY` first and won't be downloaded by `transifex-pull.sh --all`.

**Comment by tofi86** [comment]
> I guess we should wait for more translations before merging this in, correct?

I will contact the translators via Transifex to request updating their translations. Hopefully there will be some feedback :)

Can I promise that the changes will be released in a 4.1.1 version? Korean alone would be worth a bugfix release, wdyt?

**Comment by tofi86** [comment]
> Yes, sounds perfectly doable.

Awesome!

Any chance you can also tweet a link to https://github.com/w3c/epubcheck/wiki/Translating from `@epubcheck` account together with a call for action to update translations via Transifex?

**Comment by tofi86** [comment]
Also updated italian language files after pushing the old git sources to transifex, updating messages and especially the help message, and re-downloaded them.

**Comment by rdeltour** [comment]
> Any chance you can also tweet a link to https://github.com/w3c/epubcheck/wiki/Translating from `@epubcheck` account together with a call for action to update translations via Transifex?

Done!

**Comment by tofi86** [comment]
> Done!

Thanks! For reference: https://twitter.com/epubcheck/status/1067100340422623232

----

I wrote a note to the Transifex EPUBCheck community over at https://www.transifex.com/idpf/teams/28633/discussions/

Did you get a notification for that Romain?

**Comment by tofi86** [comment]
> Did you get a notification for that Romain?

Also published the post via "announcements" as I'm not sure how the Transifex notification system works...
https://www.transifex.com/idpf/epubcheck/announcements/

**Comment by tofi86** [comment]
rebased on `master` and force-pushed after PR #915 was merged.

**Comment by tofi86** [comment]
Rebased on `master` after cherry-picking some basic changes to `master`.

These changes to `master` enable translators to pull translations like `ko_KR` or `pt_BR` from Transifex.

**Comment by rdeltour** [comment]
hi @tofi86 what's the status on this PR? When should we consider it ready (some locales are still not 100% translated)?

**Comment by tofi86** [comment]
We got contirbutions for spanish, french, dutch, italian is also almost complete and new ones korean and brazilian Portuguese.

Portuguese pt_PT and pt_BR teams are about to join forces so let's see whether we also get a completely new pt_PT translation.

I would like to wait with a final call on transifex until we have merged all PR's for 4.1.1 to `master` which affect properties files. If this is all done I'd like to make the final call on transifex and give translators, say, 1 week to finish translations.

Does this sound like a plan?

**Comment by rdeltour** [comment]
> Does this sound like a plan?

yes, SGTM!

**Comment by tofi86** [comment]
I think this can be considered safe to merge now. No new changes. for `fr`, `de`, `pt_BR`, `ko_KR`, `it`, `es`, `ja`.

There are some other languages but they didn't reach 50% completion yet so I did not consider them here yet.

@rdeltour merge whenever you want to release 4.1.1.

**Comment by tofi86** [comment]
`ko_KR` has been translated 💯%! Thanks a lot!

PR ahs been updated.

**Comment by tofi86** [comment]
Thanks for rebasing @rdeltour! LGTM! Go 🚢 it! :)

**Pull request merged**
