### PR TITLE
Add l10n contributors to the dist README

### PR DESCRIPTION
**Pull request by tofi86**
I just added new translations from Transifex:
* **Chinese (Taiwan)** 46195adc2a88ef45ef6341bb424804980f3857db
* **Danish** 28ef69bea729073186890117611c616672e64fc7

I just updated existing translations from Transifex:
* **Italian** 864282a6245007a6b08d3c1d57c2da6db2da5fa0 and d954ae7b9b90d373378e3c6622ba40bb7d42f5d0

However, Transifex does not show who translated the messages, who contributed.

Dear contributors, we highly value your efforts in translation EPUBCheck and would like to add your name to the list of contributors in the README file. 🙏 

Please leave me a comment  here if you contributed to one of the languages above and I will add you to the list. Thanks.

### CODE REVIEW

**Comment by MyDK** [comment]
Hi Tobias,
Before you pull Danish, better check the number above is correct, as present '46195ad' will pull Chinese :) (You got my name right, so that is great, thanks)

**Comment by tofi86** [comment]
Thanks for the hint, but it was only a typo. This is the right commit 28ef69bea729073186890117611c616672e64fc7 and it has already been pulled. :-)

**Comment by bobbytung** [comment]
Ya, It's me, translated for Traditional Chinese.

**Comment by tofi86** [comment]
> Ya, It's me, translated for Traditional Chinese.

Perfect! I added you to the list: https://github.com/w3c/epubcheck/pull/991/files#diff-075ca30d162eca869989856ecf5c3a8bR65

**Comment by gregoriopellegrino** [comment]
Fondazione LIA for Italian (Elisa Molinari)

Thanks,
Gregorio

**Comment by rdeltour** [comment]
Hi @tofi86, hi translators,

Thank you so much for your help in localizing EPUBCheck, this is truly appreciated!

Please note that the message strings currently translated (and available via the Transifex app) are the strings contained in the `master` branch, which currently holds the v4.1.x version stream. As you probably know, we're currently working in parallel in the next version, v4.2.0; this work happens in the branch `next/v4.2.0`, and does contain a few new or modified message strings.

We will publish a release candidate in the next few weeks (before March 18). When the RC is out, we can merge back the `next/v4.2.0` branch into the `master` branch, which will make the strings available to Transifex, and ready to be translated before the final v4.2.0 release.

@tofi86, does that sound OK to you?

**Comment by tofi86** [comment]
> Fondazione LIA for Italian (Elisa Molinari)

Thanks! I added her to the list: https://github.com/w3c/epubcheck/pull/991/files#diff-075ca30d162eca869989856ecf5c3a8bR70

What about yourself?

**Comment by tofi86** [comment]
@rdeltour yes, I'm aware of that and as soon as 4.2 is released as an RC and on `master` I will write a Call for Action in Transifex to let translators and contributors know about the changes.

**Comment by gregoriopellegrino** [comment]
> > Fondazione LIA for Italian (Elisa Molinari)
> 
> Thanks! I added her to the list: https://github.com/w3c/epubcheck/pull/991/files#diff-075ca30d162eca869989856ecf5c3a8bR70
> 
> What about yourself @gregoriopellegrino ?

I reviewed the translations

**Comment by tofi86** [comment]
> I reviewed the translations

Thanks a lot! So I think I'm adding you as well, right? As `Gregorio Pellegrino`?

**Comment by gregoriopellegrino** [comment]
Ok, yes Gregorio Pellegrino (Fondazione LIA)

**Comment by MyDK** [comment]
Hallo Mr. tofi86 🤗
1: If you could add (Publizon) after my name, it would be great, please.
2: I need 1 or 2 more days to check for inconsistencies and improving the Danish messages. 
I found out, during the task, that it was very helpful to turn to your German translations for better understanding what the massage was about. So, I will run though my translations in order to improve the Danish massages, OK?

**Comment by tofi86** [comment]
>  1: If you could add (Publizon) after my name, it would be great, please.

done.


>  2: I need 1 or 2 more days to check for inconsistencies and improving the Danish messages.

sure, no problem.

**Comment by MyDK** [comment]
I have finished Danish translation.

**Comment by tofi86** [comment]
@MyDK I updated Danish messages on `master` branch. Thanks for your contribution.

I'll consider this ready to squash&merge, @rdeltour.

**Pull request merged**
