### PR TITLE
WIP: OCF compression encryption (schema experiment + additional tests)

### PR DESCRIPTION
**Pull request by danielweck**
Do not merge (Work In Progress).

This is an "extension" of https://github.com/w3c/epubcheck/pull/928

See spec.:

https://w3c.github.io/publ-epub-revision/epub32/spec/epub-ocf.html#sec-enc-compression

### CODE REVIEW

**Comment by danielweck** [comment]
Good call Romain. Thanks

**Comment by rdeltour** [comment]
Huh, in fact I hadn't realized I had closed this PR. I did delete the `next/v4.2.0` branch, so I guess this got closed at the same time 🤔. 
Should we reopen this PR in a dedicated branch?

**Comment by danielweck** [comment]
I would leave it closed. This PR may be used as a future reference for the particular "encryption" case, but the way testing was implemented in this WIP / experiment does not align well with the general case.

**Comment by rdeltour** [comment]
OK, thanks!

**Pull request closed without merging**
