### PR TITLE
feat: update to latest schemas from the Nu HTML Checker

### PR DESCRIPTION
**Pull request by rdeltour**
---------------------

Add `plaintext-only` value to `contenteditable` attribute

https://github.com/validator/validator/commit/228ea687b

---------------------

add warnings for deprecated ARIA attributes (#1560)

https://github.com/validator/validator/commit/e61fbeb2c

---------------------

disallow aria attributes on datalist (#1557)

https://github.com/validator/validator/commit/b4849c04b

---------------------

allow role=button on area

https://github.com/validator/validator/commit/89ff1fc2b

---------------------

fix: allow -1 for aria-colcount

https://github.com/validator/validator/commit/2466e73c4

---------------------

fix: Allow -1 for aria-rowcount

https://github.com/validator/validator/commit/eac205b6b

---------------------

Add `fetchpriority` attribute

https://github.com/validator/validator/commit/7c9991405

---------------------

Script type importmap (#1478)

https://github.com/validator/validator/commit/4054c56f5

---------------------

Move “manifest” attribute to legacy-attributes list

https://github.com/validator/validator/commit/175e62d3a

---------------------

Pointer Events (#1481)

https://github.com/validator/validator/commit/5eb52a931

---------------------

Report a better error message for obsolete “manifest” attribute

https://github.com/validator/validator/commit/ae924b625

---------------------

onscrollend

https://github.com/validator/validator/commit/87287a97f

---------------------

slot element

https://github.com/validator/validator/commit/d6cf423c1

---------------------

Allow paragraphs in hgroup (#1467)

https://github.com/validator/validator/commit/3ff53973f

---------------------

blocking="render" (#1466)

https://github.com/validator/validator/commit/df5d4e23a

---------------------

inert

https://github.com/validator/validator/commit/507f551b2

---------------------

hidden=until-found

https://github.com/validator/validator/commit/a424d55a8

---------------------

media attribute in meta element

https://github.com/validator/validator/commit/af3e94d22

---------------------

Sync event handlers

https://github.com/validator/validator/commit/58bea51c7

---------------------

Remove manifest attribute

https://github.com/validator/validator/commit/66510f3ca

---------------------

enterkeyhint

https://github.com/validator/validator/commit/70f3044d7

---------------------

Form method dialog (#1443)

https://github.com/validator/validator/commit/0db229a44

---------------------

imagesrcset and imagesizes in link (#1444)

https://github.com/validator/validator/commit/49656dbfc

---------------------

feat: add support width and height of source in picture

https://github.com/validator/validator/commit/176d98e4f

---------------------

Update: allow none/presentation on nav element (#1323)

https://github.com/validator/validator/commit/5e25edb39

---------------------

Update schema/html5/web-forms.rnc

https://github.com/validator/validator/commit/95ba6c7cf

---------------------

update role allowances for button and input type=button

https://github.com/validator/validator/commit/6cc14c4d7

---------------------

adds role=radio alowance to img alt=foo

https://github.com/validator/validator/commit/b013aa02b

---------------------

remove deprecated dpub role allowances

https://github.com/validator/validator/commit/b0fb152c0

---------------------

allow section element to have role=group

https://github.com/validator/validator/commit/078341d37

### CODE REVIEW

**Comment by rdeltour** [comment]
@mattgarrish, I'd like your input on this one.

This new round of update includes https://github.com/validator/validator/pull/1262/commits/cf03b5a4e94df8413a9a27b8a244bbe8c9c06d75, which removed `doc-endnote` and `doc-biblioentry` as allowed roles on `li` (apparently I didn't in fact update the schema since earlier, my bad).

While I understand the reason for the HTML checker, raising an error sound a bit drastic for EPUBCheck. I'm considering re-adding the roles to our version of the schema and raising a bespoke warning instead. WDYT?

**Comment by mattgarrish** [comment]
> raising an error sound a bit drastic for EPUBCheck

Ya, it's not like using the roles really breaks anything. The inheritance model they break is a technical spec issue not a real problem that affects AT.

They shouldn't be used anymore, but 1.1 isn't even a REC yet. A warning sounds better than an error.

**Comment by mattgarrish** [comment]
The test to catch the roles is a bit limited. It only checks for the roles on `li` instead of all elements that accept any role. Because you can have `<div role="list">`, for example, you can have `<div role="doc-endnote">` as a child of it. (See [example 18](https://www.w3.org/TR/dpub-aria-1.0/#doc-endnote) in the 1.0 spec.)

**Comment by rdeltour** [comment]
Yeah I know. That was more or less intentional, as I think this is not used a lot and the HTML validator does not catch these either.
But adding a naive fix (parent/child only) in Schematron should be straightforward.

**Comment by rdeltour** [comment]
> But adding a naive fix (parent/child only) in Schematron should be straightforward.

Or maybe even simpler: shouldn't a warning be raised whenever one of these deprecated role is used, regardless of the semantic of the holding element and ancestor?

**Comment by mattgarrish** [comment]
> shouldn't a warning be raised whenever one of these deprecated role is used, regardless of the semantic of the holding element and ancestor?

Yes, I wouldn't worry about whether there's a list ancestor or not, or what roles the element should accept. That's kind of moot. If any element has a role attribute with doc-endnote or doc-biblioentry, it should raise a warning.

**Comment by rdeltour** [comment]
Done.

**Review by mattgarrish — APPROVED** [review]

**Pull request merged**
