### PR TITLE
Update schemas from upstream Nu Html Checker sources

### PR DESCRIPTION
**Pull request by rdeltour**
This is a major schema update, to reuse the latest schemas from
the Nu Html Checker, with the following tweaks:

- adapt the integration in schema drivers
- replace the Nu Html Checker's pluggable datatype library with
  EPUBCheck’s more limited static RelaxNG datatypes
- add EPUB-specific content model extensions

Changes specific to XHTML (#892):

- keep allowing missing `title` in the `head` element (#448)
- but report missing `title` as a WARNING (with a Schematron check)
- keep allowing `meta http-equiv` in encoding declaration state
  (allowed in W3C but forbidden in WHATWG's HTML standard)
- keep allowing the `border` attribute on `table` elements
  (allowed in W3C but forbidden in WHATWG's HTML standard)
- report `aria-describedat` as a schema error (#896)
- add tests for several obsolete features which appeared in previous
  test content (`time/@pubdate`, `iframe/@seamless`, `keygen`, `menu`,
  `dropzone`, `contextmenu`, in-body `style`, `style/@Scoped`)
-  check MathML and XHTML content in `epub:switch` (#835)

Changes specific to MathML:

- use the schemas from Nu Html Checker, which are based on older
  MathML schema but bring some specific tweaks.
- re-add the changes from the newer MathML 3.0 (2nd edition) schemas
- improve the schema checks of EPUB-specific `annotation-xml`
  restrictions (notably check the combination of the `name` and
  `encoding` attributes)

Changes specific to SVG (#779, #893):

- use the schemas from Nu Html Checker, which are based SVG 1.1

Changes specific to Navigation Documents:

- do not check the presence of mandatory headings on `nav` elements
  with no `epub:type` attribute

### CODE REVIEW

**Comment by danielweck** [comment]
Related PR:
https://github.com/w3c/epubcheck/pull/927

**Comment by murata2makoto** [comment]
Why do we need inkscape-draft.rnc?

**Comment by rdeltour** [comment]
> Why do we need inkscape-draft.rnc?

TBH I'm not sure. For now I "just" copied over the schemas used and referenced by the Nu Html Checker. In fact I was wondering the same, but haven't had the time to look it up in detail yet.

I'm assuming it contains pattern definitions useful to general SVG checking, but again to be taken with a grain of salt before a more detailed look.

**Comment by murata2makoto** [comment]
Do you plan to introduce custom Java codes in  [Nu Html Checker ](https://github.com/validator/validator) as well?  In my understanding, such codes and schemas in the Nu Html Checker are intended to be used together.  However, even if epubcheck borrows schemas only, I suppose that the result will be already a big improvement.

**Comment by rdeltour** [comment]
> Do you plan to introduce custom Java codes in [Nu Html Checker ](https://github.com/validator/validator) as well?

Unfortunately, a full integration of the Nu Html Checker is out of scope for v4.2.0, which aims at bringing EPUB 3.2 support to the community as soon as possible.

That said, I totally agree that there's only so much the schemas can do, and a (very) significant part of the Nu Html Checker’s functionality resides in its Java code. We do intend to experiment with a full integration, later down the road, but it’s a more ambitious refactoring.

For now, as you say the schemas are already a big improvement!

**Comment by mattgarrish** [comment]
One more spec inconsistency I found validating the samples: W3C allows the `border` attribute on tables but the schemas/WHATWG do not.

I think we need to override and allow, as I suspect this could affect a lot of people.

Otherwise, the schemas caught all the same issues as before plus a lot of new legitimate problems. Definitely looking like a good upgrade.

**Comment by rdeltour** [comment]
> One more spec inconsistency I found validating the samples: W3C allows the `border` attribute on tables but the schemas/WHATWG do not.
> 
> I think we need to override and allow, as I suspect this could affect a lot of people.

Ok, I'll override this.

I'm wondering how we could get reasonably representative stats on existing EPUB content. That would be super useful.

**Pull request merged**
