### PR TITLE
[WIP] [fix #676] Add support for EDUPUB dc:type "education"

### LINKED ISSUE #676: EDUPUB's new dc:type is "education"
EDUPUB, now known as EPUB for Education, was previously identified with a `dc:type` of "edupub", it has been now renamed to "education".

The EDUPUB validation profile should be triggered for both values, and an INFO message should be triggered when "edupub" is found.

### PR DESCRIPTION
**Pull request by rdeltour**
Fixes #676

### CODE REVIEW

**Comment by mattgarrish** [comment]
I wouldn't expend much effort making edupub work anymore. I don't get the impression it's long for this world as a profile.

**Comment by rdeltour** [comment]
> I wouldn't expend much effort making edupub work anymore. I don't get the impression it's long for this world as a profile.

Right. But it wasn't too costly a change, and was the opportunity to improve a couple things (see the first 2 commits) :-)

**Comment by rdeltour** [comment]
> OPF-064 isn't covered by a test anymore.

Damned. Forgot to test the coverage test, which I usually disable in my dev setup. I'll have a look.

**Comment by tofi86** [comment]
@rdeltour can you please have another look at this in the next 2 weeks? Otherwise I'll postpone it to the backlog.

**Comment by tofi86** [comment]
Removing from 4.1.0 milestone. Feel free to work on it and assign it back to 4.1.0 as long as we're still working on it.

**Comment by rdeltour** [comment]
Closing this old PR, since additional support  for EDUPUB is currently out of scope.

**Pull request closed without merging**
