### PR TITLE
feat: update translations for 4.2.0

### PR DESCRIPTION
**Pull request by tofi86**
pulled from Transifex. Thanks to the contributors and translators! 👏 🎉

### CODE REVIEW

**Comment by rdeltour** [comment]
Is this PR supposed to be augmented as we get more translations, or is it easier to merge this ASAP?

**Comment by tofi86** [comment]
Sorry, forgot the WIP prefix. This is just the first batch of translations, I hope there’s more to come.

**Comment by tofi86** [comment]
@rdeltour reviewed, translated missing german keys and pulled again with `-all`, adding another korean update.

You'Re ready to go :-) 🚢

**Comment by rdeltour** [comment]
Cool, thank you @tofi86!

**Pull request merged**
