### PR TITLE
Allow foreign ns elements and attributes in svg content docs

### PR DESCRIPTION
**Pull request by mattgarrish**
(Resubmitting branched off next/v4.2.0 this time.) 

I believe this NVDL accomplishes what is needed for #491. It attaches XHTML elements as well as epub:, xlink: and xml: attributes, as well as attributes in no namespace. Elements and attributes from any other namespace are blanket allowed.

The empty pattern in the sch file is annoying, but without it oxygen was complaining that a required pattern was missing. Seems to be harmless, but feel free to comment it out.

### CODE REVIEW

**Comment by murata2makoto** [comment]
I reviewed the NVDL script.  It looks good to me, but I would like to use a mode name different from "attach".  This mode does not attach foreign elements or attributes.

**Comment by mattgarrish** [comment]
What about calling it allowForeignNS?

**Comment by rdeltour** [comment]
I updated the PR:

- added code in the XML Parser to allow the `data-*` attributes by removing them at parsing time
- tweaked the NVDL to attach all namespaces to the Schematron validation
- tweaked the NVDL to set a stricter HTML-only mode to the RelaxNG validation in the context of a `foreignObject` element.

I took the opportunity to update Jing to v20181222 (which fixes #859 without us having to provide a hack, and even from an NVDL schema factory).

@mattgarrish I couldn't assign you to review your own PR, but if you can have a quick look… 😉

**Comment by mattgarrish** [comment]
LGTM!

**Pull request merged**
