### PR TITLE
[WIP] Nordic epub rules

### PR DESCRIPTION
**Pull request by kalaspuffar**
Hi.

I'm contributing a new function to the checker and I'm not sure if it's in scope.

The DAISY Consortium (http://www.daisy.org/) has authored a format called dtbook used for the production of papers readable by a host of readers.

They have a converter that can convert between epub and dtbook. (https://github.com/nlbdev/nordic-epub3-dtbook-migrator) and in order to create a valid epub for the dtbook format, there is a guideline/specification implemented for the Nordic region.

The contribution in this pull request adds the schemas required to validate this format using the epubcheck. Adding this to the tool will make it possible to validate a nordic epub without having to start the entire DAISY Pipeline tooling.

Best regards
Daniel

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @tofi86

This check is in WIP just because it checks most of the rules of the Nordic format.

The .sch and .rnc files check most of the issues. These files are used in the daisy pipeline tooling and then it will also check that all references are correct, that the play order is in increasing order a.s.o.

The reference checking is something requiring checks on multiple files and I've not figured out how the structure of epub check enables this feature.

Maybe you can point me in the right direction?

Best regards
Daniel

**Comment by tofi86** [comment]
Hi Daniel,

thanks for this contribution. A new profile for this use case seems very specific and I'm not sure whether I can decide to merge or not. This should probably be discussed on the EpubCheck mailing list or probably also on the next call this thursday. Any chance you can make it on the call and give us a short introduction for this use case?

Regarding the code question, I'm afraid I can't help you. While I'm helping to maintain this project I'm more the bug fixing and issue triaging guy and not the one implementing bold new features. That's Romain's part ;-) and he's way more into the code than I am. Probably he can help...

(cc @rdeltour @TzviyaSiegman)

**Comment by rdeltour** [comment]
Closing this PR (sorry for the late closure). Adding support for unofficial profiles is out of the scope of EPUBCheck. We can do our best to add or improve the extensibility hooks to make them possible, but we won't maintain these extensions in the main repository.

But if extensibility hooks are needed, feel free to open a new feature request!

**Comment by kalaspuffar** [comment]
Hi @rdeltour 

Thank you for telling me about the closure and the reason for it..

We are currently helping the agencies in the nordic region to update these rules to comply with the new specification.

https://format.mtm.se/nordic_epub/2020-1/

One of the questions they asked during this work was how extensive the validation of XHTML was done in epub check as they are going to run EPUBCheck -> nordic validator -> ACE in series in order to ensure good output.

And having correct XHTML check makes the rule work easier as we don't have to add those kind of checks..

If you wonder about ACE then it's an epub validator for accessibility using the axe engine under the hood.

"Ace by DAISY, Accessibility Checker for EPUB | Inclusive Publishing" https://inclusivepublishing.org/toolbox/accessibility-checker/

Great to hear that work is still going on with EPUBCheck have not heard anything for a while.

Best regards
Daniel

**Pull request closed without merging**
