### PR TITLE
Release v4.1.1

### PR DESCRIPTION
**Pull request by rdeltour**

### CODE REVIEW

**Comment by tofi86** [comment]
Suggestion: List 'Features' before 'Bug Fixes'

**Comment by rdeltour** [comment]
> Suggestion: List 'Features' before 'Bug Fixes'

I can do that in the release notes. However the changelog is automatically generated, so I prefer to leave it as-is!

**Comment by rdeltour** [comment]
Release draft is available 🙂

**Comment by tofi86** [comment]
> However the changelog is automatically generated, so I prefer to leave it as-is!

Okay, I almost thought so...

**Pull request merged**
